name:                hspl
version:             0.1.0.0
github:              "Yannik/hspl"
license:             GPL-3
author:              "Yannik Sembritzki, Steven Meyer"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Yannik/hspl#readme>

dependencies:
- base >= 4.7 && < 5
- safe

library:
  source-dirs: src

executables:
  hspl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspl

tests:
  hspl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspl
